import Head from "next/head";
import Image from "next/image";
import Main from "../components/Main";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <div className="w-full">
      <Head>
        <title>Home Service</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Main />
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Magni dolores
      atque illum corporis voluptatum incidunt quo quaerat sapiente libero quae,
      aperiam maxime expedita perspiciatis architecto alias optio nobis commodi
      minima. Dignissimos consectetur, recusandae quis facere molestiae unde
      doloremque aperiam asperiores qui sed nulla voluptates deleniti ex
      accusamus? Praesentium minus facilis porro saepe officiis esse tempore
      repudiandae ab tempora! Molestiae, ex. Veniam nam, velit explicabo quas
      unde, quos iusto placeat quis quibusdam sunt, quam deserunt. Ad excepturi
      numquam laboriosam dolorum labore odio illum neque qui, iusto consectetur
      sequi pariatur ratione reprehenderit. Consequatur incidunt impedit sequi,
      sapiente! Possimus nobis temporibus iure, commodi assumenda repellendus
      libero facere, incidunt facilis, rem deserunt. Voluptates incidunt ea
      aliquid atque perferendis dicta, natus ducimus deserunt illum excepturi
      quasi? Cum possimus, doloremque minima eius laborum mollitia eligendi
      ullam veniam veritatis esse, dicta, numquam quod hic consectetur!
      Consequatur nostrum eveniet soluta. Expedita officia iste magnam
      voluptates saepe ea dignissimos animi dolores tempora ab numquam quasi
      quis atque, provident, placeat esse natus soluta necessitatibus reiciendis
      corrupti earum veniam! Harum eaque iusto saepe inventore consectetur est
      blanditiis perferendis eligendi, excepturi soluta totam voluptas cumque
      ratione commodi, quam placeat! Doloremque tempora fugit enim iure ea
      totam, delectus dicta recusandae. Veritatis! Dolorum, incidunt
      repellendus! Iure necessitatibus incidunt maxime tempore quasi repellat
      corrupti dicta minima magni, itaque fugit provident voluptates neque
      cumque officiis, suscipit modi consequuntur, ipsum eveniet atque veniam
      possimus? Provident. Officia aperiam quisquam, adipisci, minus error
      suscipit consectetur debitis, voluptatibus consequatur laudantium repellat
      molestias incidunt id rerum? Itaque illum pariatur at blanditiis dicta,
      quidem, molestiae laudantium reiciendis, impedit suscipit autem.
      Laudantium possimus, dicta facilis adipisci labore exercitationem laborum
      quo iusto at rerum incidunt molestias odit corporis perspiciatis
      necessitatibus sapiente? Similique distinctio possimus unde est totam, eos
      esse dolores incidunt doloribus. Enim beatae est in temporibus odio
      voluptates unde ab amet magni eius possimus esse, illo repudiandae nulla
      maxime consequuntur maiores et id. Iste ipsum possimus delectus hic
      doloribus incidunt dolor! Blanditiis sit ut harum! Rerum aut obcaecati
      sequi maxime molestiae quos beatae accusantium voluptates. Nobis,
      voluptates veritatis, incidunt inventore ut qui vero numquam
      necessitatibus maxime, voluptatum voluptatem quis atque labore? Eum
      consequatur optio, voluptatum nisi tenetur saepe. Ex, voluptatibus
      pariatur! Natus cumque aperiam temporibus nisi. Tempora similique unde
      illum molestias voluptatem! Nemo eveniet necessitatibus iusto fuga iure,
      quibusdam nulla explicabo. Molestiae voluptas repudiandae veritatis non
      quaerat natus, recusandae facere maiores blanditiis error quia enim, atque
      ducimus autem, sunt aut placeat necessitatibus aspernatur? Magnam, porro?
      Aspernatur quisquam dolores necessitatibus animi amet. Dolore ipsa
      repellendus tempore temporibus similique ullam rem officia earum aperiam
      eligendi vitae, facere quae. Quae facere ex accusantium deserunt adipisci!
      Deserunt aliquid ad itaque ratione culpa officia temporibus quisquam. Nam
      odit magni libero hic recusandae ex aperiam. Ad minima voluptatum sed sunt
      neque eveniet tempora obcaecati illo! Unde earum quia eveniet! Eius nemo
      perspiciatis minus blanditiis reiciendis, nostrum aliquam. Dolor,
      nesciunt. Laudantium, optio aliquam harum amet quaerat, consequuntur nobis
      doloremque accusantium maxime fugiat blanditiis dolorum maiores vero fuga
      placeat eos, magnam nemo at pariatur eius ullam reprehenderit officia.
      corporis dolorum soluta unde ipsum quidem sapiente sequi mollitia laborum
      sint officiis neque, quod nihil. Odio corporis earum, ipsam vel quae
      officia error sequi provident!
    </div>
  );
}
